baseURL = 'https://rclachance.com'
languageCode = 'en-us'
title = 'RC Lachance'
theme = 'hyde'

[params]
  description = "ML & Safety Engineering"
  themeColor = "theme-base-08"
  layoutReverse = false
  disqusShortname = ""
  googleAnalytics = ""
